### ISSUE TITLE
Colour code not reflecting 

### ISSUE THREAD

**Issue by patelanjali07** [qlik-oss/sn-pivot-table#156]
When we are trying to embed the QLIK visuals using sn-pivot-table , colour codes for the cell are not reflecting in our application where as present in the QLIK. Any help would be appreciated.

**Comment by cbt1** [comment]
@patelanjali07 Are you talking about coloring the cells via a theme?

**Comment by patelanjali07** [comment]
> cbt1
Thanks for the response!
I am here talking about the background color of the cell as per the expressions. Also, when we are rendering the other visual type as sn-combo-chart / sn-bar-chart we get the color formatting as is (1:1) on qlik. However, same is not the case with sn-pivot-table.

**Comment by cbt1** [comment]
Color by expression is not something that is supported by the sn-pivot-table yet. Hopefully in the near future we can add support for it.

**Comment by cbt1** [comment]
It's now possible to color cells using Theme, Styling Panel (`components` def) and by expression.
