### ISSUE TITLE
Native pivot table from Qlik not loading

### ISSUE THREAD

**Issue by pau-garrido** [qlik-oss/sn-pivot-table#192]
Hello, 

We are migrating our mashups from Capabilities API to Nebula.JS, we are using the visualizations from Nebula. The versions of our packages are those:
  - "@nebula.js/stardust": "^3.0.4"
  - "@nebula.js/sn-table": "^1.19.1"
  - "@nebula.js/sn-bar-chart": "^1.25.0"
  - "@nebula.js/sn-line-chart": "^1.20.0"
  - "@nebula.js/sn-combo-chart": "^1.19.6"
  - "@nebula.js/sn-pivot-table": "^1.0.1"
  - "@nebula.js/sn-scatter-plot": "^3.32.0"

We are not rendering the visualizations on the fly, we are using the id from Qlik to render existing master objects. All the visualizations are working fine except the pivot-table, which we are not able to render and no errors are displaying. 

Can you give us some help? We also tried it using stardust  2.x version and is not working.

Thanks,
Pau Garrido

**Comment by enell** [comment]
Hi @pau-garrido 
If you are still having issue I would advise you to use then nebula.js channel in https://qlikdeveloper.slack.com/ instead. You will gett better discussions and answers there
